### ISSUE TITLE
add `--debug` flag

### ISSUE THREAD

**Issue by rimusz** [helm/helm-2to3#31]
that should to show more detailed output

**Comment by rimusz** [comment]
it would allow to debug such issue as #30

**Comment by hickeyma** [comment]
@rimusz At the moment, the plugin is quite verbose on each action it is performing. This is to make the caller aware of the command running and the operations being performed for that command. This would be expected trace for such a tool like the plugin.

Here is an example of the convert output:

```console
$ 2to3 convert chrt-v2 --delete-v2-releases
2019/10/03 06:14:17 Release "chrt-v2" will be converted from Helm v2 to Helm v3.
2019/10/03 06:14:17 [Helm 3] Release "chrt-v2" will be created.
2019/10/03 06:14:17 [Helm 3] ReleaseVersion "chrt-v2.v1" will be created.
2019/10/03 06:14:17 [Helm 3] ReleaseVersion "chrt-v2.v1" created.
2019/10/03 06:14:17 [Helm 3] Release "chrt-v2" created.
2019/10/03 06:14:17 [Helm 2] Release "chrt-v2" will be deleted.
2019/10/03 06:14:17 [Helm 2] ReleaseVersion "chrt-v2.v1" will be deleted.
2019/10/03 06:14:17 [Helm 2] ReleaseVersion "chrt-v2.v1" deleted.
2019/10/03 06:14:17 [Helm 2] Release "chrt-v2" deleted.
2019/10/03 06:14:17 Release "chrt-v2" was converted successfully from Helm v2 to Helm v3.
```

Re issue #30, the plugin did its job and returned all information information to the caller that the release version already existed as follows:

```console
$ helm3 2to3 convert -t ns1 xxx
Release "xxx" will be converted from Helm 2 to Helm 3.
[Helm 3] Release "xxx" will be created.
[Helm 3] ReleaseVersion "xxx.v1" will be created.
Error: release: already exists
Error: plugin "2to3" exited with error
```
The difficult with this issue was that it did not show when the use did a `helm list` in the Helm v3 system. This was because the release version storage object had a clash between v2 and v3, which was because of a bug in Helm core. This required some deep troubleshooting. Debug would not have helped in this situation.

I am interested to understand where you would like the debugging on top of the tracing that plugin already shows?

**Comment by rimusz** [comment]
@hickeyma fair enough answer, we can close this issue then.
