### ISSUE TITLE
Helm 3 dependency update fails after migration

### ISSUE THREAD

**Issue by cringdahl** [helm/helm-2to3#32]
OS: macOS

After a `helm3 move config`, a `helm3 dep update` bails due to the error:

`Error: open /Users/username/Library/Caches/helm/repository/local-index.yaml: no such file or directory`

Copying the `.helm/repopsitory/cache/local-index.yaml` to the specified location results in a successful dependency update.

The 2to3 plugin should copy this file.

**Comment by rimusz** [comment]
local repo as it is no longer supported in v3, this why the files wasn't copied

**Comment by cringdahl** [comment]
Why is there an error as though helm3 is looking for it?

**Comment by hickeyma** [comment]
@cringdahl There are some differences between cache in Helm v2 and Helm v3 which don't align. Therefore, the configuration migration copies the repository file and not the local repositories. These need to be re-aligned in Helm v3 as is now documented by the changes in PR https://github.com/helm/helm-2to3/pull/56. 

Rather than copying over the local repository, would suggest removing it with `repo remove` and only re-add if need be.

FYI, In Helm v3 no repositories are added OOTB. So, no `stable` and `local`.

**Comment by cringdahl** [comment]
Will this be documented or produce an error? This seems like it will be a common error for future migrators.
